In [34]:
import numpy as np

Implement a class for handling tempature data.

The data file is in 'data' folder. The data consists of 32 days (5/25-6/25).

In [35]:
class TempatureData:
    def __init__(self, csv_path):
        self.raw_data = np.genfromtxt(csv_path, delimiter=',')

    def get_previous_hours(self, base_hour, k) -> np.array:
        if not (1 <= base_hour and base_hour <= 24):
            return
        if not (1 <= k and k <= 24):
            return 
        
        total_days = 30
        tempature_array = np.zeros(shape=(total_days, k))

        data_raw_start = base_hour - k - 1 
        # if the first day is skipped
        if base_hour <= k:
            data_raw_start += 24

        for day in range(total_days):
            tempature_array[day] = self.raw_data[data_raw_start:data_raw_start+k, -1]
            data_raw_start += 24

        return tempature_array

temp_data = TempatureData('data/wakamatu_tempature.csv')
temp_data.get_previous_hours(1, 24)

[[2.023e+03 5.000e+00 2.500e+01 1.000e+00 8.600e+00]
 [2.023e+03 5.000e+00 2.500e+01 2.000e+00 7.900e+00]
 [2.023e+03 5.000e+00 2.500e+01 3.000e+00 7.400e+00]
 [2.023e+03 5.000e+00 2.500e+01 4.000e+00 7.000e+00]
 [2.023e+03 5.000e+00 2.500e+01 5.000e+00 6.600e+00]
 [2.023e+03 5.000e+00 2.500e+01 6.000e+00 8.300e+00]
 [2.023e+03 5.000e+00 2.500e+01 7.000e+00 9.700e+00]
 [2.023e+03 5.000e+00 2.500e+01 8.000e+00 1.100e+01]
 [2.023e+03 5.000e+00 2.500e+01 9.000e+00 1.290e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.000e+01 1.510e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.100e+01 1.630e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.200e+01 1.840e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.300e+01 1.960e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.400e+01 2.180e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.500e+01 2.280e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.600e+01 2.260e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.700e+01 2.240e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.800e+01 2.080e+01]
 [2.023e+03 5.000e+00 2.500e+01 1.900e+01 1.90

array([[ 8.6,  7.9,  7.4,  7. ,  6.6,  8.3,  9.7, 11. , 12.9, 15.1, 16.3,
        18.4, 19.6, 21.8, 22.8, 22.6, 22.4, 20.8, 19. , 16.9, 16.8, 15.2,
        14.5, 13.9],
       [13.1, 12.3, 11.6, 11.5, 11.5, 12.6, 14.4, 16. , 16.5, 18.4, 20. ,
        19.8, 20.7, 21.6, 22. , 21.6, 20. , 18.5, 18. , 17.1, 16.3, 16.1,
        15.8, 15.2],
       [14.9, 14.7, 15. , 14.8, 14.7, 15.2, 16.6, 18. , 20. , 21.8, 23.8,
        24.9, 26.6, 26.2, 25.9, 26.6, 25.8, 25.5, 24.2, 23.1, 21.5, 19.9,
        19.6, 19. ],
       [19.4, 18.7, 18.3, 18. , 17.7, 18.5, 19.5, 20.9, 21.4, 23.1, 24.4,
        24.5, 25.4, 23.8, 22.7, 21.9, 21. , 20.2, 19.9, 18.3, 18. , 18. ,
        17.4, 17. ],
       [16.8, 16.9, 16.7, 16.6, 16.5, 16.5, 17. , 17.6, 17.6, 18.1, 18.4,
        18.6, 18.6, 20. , 19.7, 19.8, 19.8, 19. , 18.7, 18.7, 18.6, 18.6,
        18.5, 18.2],
       [18.2, 18. , 17.7, 17.7, 17.6, 17.7, 17.9, 20.3, 21.6, 23. , 23.9,
        22.5, 23.2, 23.1, 22.4, 21.9, 20.8, 19.7, 18.3, 17.4, 16.9, 16.2,
       

In [ ]:
# Linear regression
class LinearRegression:
    def __init__(self, ):
        pass

    def train(self):
        pass

    def predict(self):
        pass

In [ ]:
# train
train_data = data
test_data = data
model = LinearRegression()
model.train(train_data)

In [ ]:
# predict

# past 24h
model.predict(test_data)

# k=